# $Id: dropalltables.sql,v 1.1.1.1 2003/06/02 21:34:59 vagnerr Exp $

# Copyright (C) 2003-  Peter J. Wise <peter_at_bloodaxe.com>
# This code is protected under the Gnu Public License (See LICENSE).

drop table AGENCY,AGENCYCONTACT_LNK,AGENT,AGENTCONTACT_LNK,COMPANY,COMPANYCONTACT_LNK,CONTACTTYPE_CONST,JOB,JOBAGENT_LNK,JOBDATA,JOBDATATYPE_CONST,JOBNOTES,JOBRELATED_LNK,KEYWORD_CONST,KEYWORD_LNK,LOCATION_CONST,NEXTACTION_CONST,SOURCE_CONST,STATUS_CONST,TYPE_CONST;
